name: publish
on: 
  workflow_dispatch:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: | 
        echo "VERSION=${GITHUB_REF#refs/*/:1}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build Common.DatabaseInfrastructure.sln --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test Common.DatabaseInfrastructure.sln --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: dotnet pack Common.DatabaseInfrastructure.sln --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push NuGet.Workflow.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key {{ NUGET_APIKEY }}